### ISSUE TITLE
Adding date

### ISSUE THREAD

**Issue by kbaum** [pauldowman/better_logging#1]
Wouldn't it be useful to have the date with the time?

thx

**Comment by pauldowman** [comment]
Yes, but that would take up more space on every line (making it a bit less readable). Since Rails logs have the date printed on every HTTP request it seems a bit unnecessary because you're never very far away from a line that has the full date on it.

**Comment by kbaum** [comment]
True, but it's a pain to scroll up and down to figure out what time something happened.  Also, if it's a non-traditional rails app, you could be logging from a daemon process or something similar.  I think it would make sense to make the date format to be configurable.

Btw, this is a great plugin.  Something like this should be a part of rails.

**Comment by pauldowman** [comment]
I agree, it would be nice to have the date format as a configurable option. If anyone wants to submit a patch please do! :-)

BTW, I do have several daemon processes that log to my Rails log, but I also rotate my logs daily so I guess that might be why it hasn't been an issue for me.

**Comment by pauldowman** [comment]
I was going to re-open this issue, but I can't figure out how!
