### ISSUE TITLE
fails with "uninitialized constant... ActiveRecord" when using Rails without a database

### ISSUE THREAD

**Issue by bobics** [pauldowman/better_logging#2]
To use Rails without a database, you must remove the Active Record framework -- this is noted in the default environment.rb file:

```
config.frameworks -= [ :active_record ]
```

If you disable Active Record, the better_logging plugin fails since it uses the ActiveRecord::Base.colorize_logging parameter.  The error displayed is:

```
Error during failsafe response: uninitialized constant ActiveSupport::BufferedLogger::ActiveRecord
```

As a workaround, I commented out the colorizing section.

**Comment by pauldowman** [comment]
Fixed in 06d3cb081555f8cc906b0d8e3357e59cfe57c22d. Let me know if you still have issues.
