### ISSUE TITLE
Custom string and current_user

### ISSUE THREAD

**Issue by vptcnt** [pauldowman/better_logging#9]
Hi

Nice gem ;-)
Is it possible to use the "custom string" o display the current_user ?

Thanks
Vincent

**Comment by pauldowman** [comment]
I guess you could set it to the current user, and then unset it after each request, but I wouldn't recommend it, it's a class variable. It might work but it wasn't really intended for that.

**Comment by skwp** [comment]
@vptcnt I myself have used Thread.current['current_user'] for this in the past
